version: "3.6"

services:
  postfix:
    image: catatnight/postfix:latest
    hostname: postfix.localhost
    restart: always
    environment:
      TZ: Europe/Zurich
      # Uncomment to enable debugging messages:
      #LOGXI: '*'
      maildomain: hacking-lab.com
      smtp_user: ivan.buetler:EBp5CJNcykf7cgmb,no-reply:FIj8qVxZXINXjJOC
    volumes:
      - ./postfix/install.sh:/opt/install.sh
    labels:
      traefik.enable: false
    ports:
      - "25:25"
      - "587:587"

